// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDailyMeals(arg1, arg2) {
  return window['go']['main']['App']['GetDailyMeals'](arg1, arg2);
}

export function GetRecommendation(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRecommendation'](arg1, arg2, arg3);
}
