// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDailyMeals(arg1:string,arg2:number):Promise<Array<main.Meal>>;

export function GetRecommendation(arg1:string,arg2:string,arg3:number):Promise<Array<main.Place>>;
